mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
   - "27017:27017"
  volumes:
   - ./mongo:/data/db:rw
  volume_driver: local
hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
hygieia-ui:
  image: hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api


hygieia-github-scm-collector:
  image: hygieia-github-scm-collector:latest
  container_name: hygieia-github
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
# place any values you want to change in docker-compose.override.yml
#  environment:
#  - GITHUB_HOST=github.com
#  - GITHUB_CRON='0 0/5 * * * *'
#  - GITHUB_COMMIT_THREASHOLD_DAYS=15


hygieia-jira-feature-collector:
  image: hygieia-jira-feature-collector:latest
  container_name: hygieia-jira
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
        # you can override these by creating a docker-compose.overider.yml and put in entries like this:
        #REQUIRED Entries
  - JIRA_BASE_URL=https://jira.atlassian.com
        #64-bit encoded credentials with the pattern username:password
        #on a mac you con create them with : echo "username:password" | base64
        #reference:  https://www.base64decode.org/
  - JIRA_CREDENTIALS=username:password

        #OPTIONAL - you may want ot tweek these
#  - JIRA_CRON="0 * * * * *"
        #Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
#  - JIRA_DELTA_START_DATE=2015-03-01T00:00:00.000000
#  - JIRA_MASTER_START_DATE=2008-01-01T00:00:00.000000

        #OPTIONAL Overrides if you need them
        #Page size for data calls (Jira maxes at 1000)
#  - JIRA_PAGE_SIZE=1000
        #Jira Connection Details
#  - JIRA_PROXY_URL=
#  - JIRA_PROXY_PORT=
        # Trending Query:  Number of days in a sprint (not-required)
#  - JIRA_SPRINT_DAYS=60
        # Trending Query:  Length of sprint week (not-required)
#  - JIRA_SPRINT_END_PRIOR=7
        #Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
#  - JIRA_SCHEDULED_PRIOR_MIN=2
        #Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
#  - JIRA_DELTA_COLLECTOR_ITEM_START_DATE=2008-01-01T00:00:00.000000
        #Jira Connection Details
#  - JIRA_QUERY_ENDPOINT=rest/api/2/
        #OAuth2.0 token credentials (currently not supported in this version)
#  - JIRA_OAUTH_AUTH_TOKEN=sdfghjkl==
#  - JIRA_OAUTH_REFRESH_TOKEN=sdfagheh==
#  - JIRA_OAUTH_REDIRECT_URL=uri.this.is.test:uri
#  - JIRA_OAUTH_EXPIRE_TIME=234567890987


hygieia-jenkins-build-collector:
  image: hygieia-jenkins-build-collector:latest
  container_name: hygieia-jenkins-build
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
# place any values you want to change in docker-compose.override.yml
#  environment:
#Jenkins server (required) - Can provide multiple
#  - JENKINS_MASTER=ttp://jenkins.company.com
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#  - JENKINS_OP_CENTER=http://username:token@jenkins.company.com
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
#  - JENKINS_USERNAME
#  - JENKINS_API_KEY
#  - JENKINS_CRON=0 0/5 * * * *
#Determines if build console log is collected - defaults to false
#  - JENKINS_SAVE_LOG=true

hygieia-jenkins-cucumber-test-collector:
  image: hygieia-jenkins-cucumber-test-collector:latest
  container_name: hygieia-jenkins-cucumber
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
# place any values you want to change in docker-compose.override.yml
#  environment:
#Jenkins server (required) - Can provide multiple
#  - JENKINS_MASTER=ttp://jenkins.company.com
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#  - JENKINS_OP_CENTER=http://username:token@jenkins.company.com
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
#  - JENKINS_USERNAME
#  - JENKINS_API_KEY
#  - JENKINS_CRON=0 0/5 * * * *
#Determines if build console log is collected - defaults to false
#  - JENKINS_SAVE_LOG=true

